[package]
name = "materialui"
version = "0.6.0"
edition = "2021"

[lib]
name = "mui"
path = "src/lib.rs"

[[bin]]
name = "example"
path = "src/example/bin.rs"


[dependencies]
nvg = "0.5.11"
glutin = "0.28.0"

